apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: kubedeschedulers.operator.openshift.io
spec:
  group: operator.openshift.io
  names:
    kind: KubeDescheduler
    listKind: KubeDeschedulerList
    plural: kubedeschedulers
    singular: kubedescheduler
  scope: Namespaced
  subresources:
    status: {}
  versions:
  - name: v1beta1
    served: true
    storage: true